from typing import Protocol, Optional
from app.domain.events.base import DomainEvent

class EventBus(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def publish(self, event: DomainEvent, topic: Optional[str] = None, key: Optional[str] = None) -> None: ...
