name: Runtime Deploy (Turbo)

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string

jobs:
  runtime:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

     
      - name: Terraform init
        run: terraform -chdir=infra/terraform init -reconfigure

      - name: Read terraform outputs
        run: |
          echo "BASTION_HOST=$(terraform -chdir=infra/terraform output -raw bastion_public_ip)" >> $GITHUB_ENV
          echo "ENDPOINTS_JSON<<EOF" >> $GITHUB_ENV
          terraform -chdir=infra/terraform output -json service_endpoints >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_QA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy runtime (Turbo decides)
        env:
          SSH_USER: ec2-user
          REMOTE_DIR: /home/ec2-user/runtime
        run: |
          npx turbo run deploy \
            --filter=runtime-* \
            --since=${{ inputs.base }}
