name: Full Pipeline

on:
  push:
    branches: [features, qa, main]
  workflow_dispatch:

jobs:
  infra:
    uses: ./.github/workflows/infra-apply.yml
    secrets: inherit

  runtime:
    needs: infra
    uses: ./.github/workflows/runtime.yml
    with:
      base: ${{ github.event.before }}
    secrets: inherit


  services:
    needs: runtime
    uses: ./.github/workflows/build.yml
    secrets: inherit
