name: Pipeline (Infra → Runtime → Services)

on:
  push:
    branches: [features, qa, main]
  workflow_dispatch:

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ steps.filter.outputs.infra }}
    steps:
      - uses: actions/checkout@v4

      
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infra:
              - 'infra/**'
              - '.github/workflows/infra-apply.yml'

  infra:
    needs: detect
    if: needs.detect.outputs.infra_changed == 'true'
    uses: ./.github/workflows/infra-apply.yml
    secrets: inherit

  runtime:
    needs: [detect, infra]
    uses: ./.github/workflows/runtime.yml
    with:
      base: ${{ github.event.before }}
    secrets: inherit

  services:
    needs: runtime
    uses: ./.github/workflows/build.yml
    with:
      base: ${{ github.event.before }}
    secrets: inherit

